### ISSUE TITLE
Error "Binary type 'Buffer' is not supported." when I call handler.process.

### ISSUE THREAD

**Issue by vlaktion** [alonrbar/easy-template-x#5]
Hello. I have an error "Binary type 'Buffer' is not supported." when I call handler.process. But handler.getText and getXml work fine.

const templateFile = await fs.readFileSync( exportDir + fileName);

            const data = {
                Country: country,
            };

            const handler = new TemplateHandler({
                delimiters: {
                    start: '{',
                    end: '}'
                }
            });

            const doc = await handler.process(templateFile, data);

**Comment by jjhbw** [comment]
Interesting, I just experienced the same issue. On `Node.js v12.8.1`.
No problems in the browser.

**Comment by alonrbar** [comment]
Hi,
Just installed node v12.8.1 and ran the tests but unfortunately was unable to reproduce the issue.
I've tried both on the master branch (v0.5.1) and the develop branch.

Maybe you can provide a stack trace or additional info?

**Comment by alonrbar** [comment]
Actually, the code that throws must be these lines from the [binary.ts file](https://github.com/alonrbar/easy-template-x/blob/master/src/utils/binary.ts):

```typescript
if (typeof Buffer !== 'undefined' && binary instanceof Buffer)
    return 'nodebuffer';

throw new Error(`Binary type '${(binary as any).constructor.name}' is not supported.`);
```

Maybe run the code in a debugger and check why the above `if` statement fails.

**Comment by alonrbar** [comment]
Ok, found the source of the error. In short the Buffer constructor is overridden somewhere during the build. I've released a new version (0.5.2) to npm.

**Comment by jjhbw** [comment]
Oh huh, interesting stuff... Nice find! 👏

**Comment by wahabshah** [comment]
I am still getting the same error using **v0.7.1** and with node **v8.9.4** or **v12.0.0**.
Stack Trace is following:-
```sh
"Error: Binary type 'Buffer' is not supported.
    at Function.toJsZipOutputType (/home/hacker/env/js-recursive-test/node_modules/easy-template-x/dist/easy-template-x.js:6833:11)
    at Zip.export (/home/hacker/env/js-recursive-test/node_modules/easy-template-x/dist/easy-template-x.js:6891:52)
    at Docx.export (/home/hacker/env/js-recursive-test/node_modules/easy-template-x/dist/easy-template-x.js:3586:33)
    at <anonymous>"
```

`package.json` has the following dependencies :-

```js
  "dependencies": {
    "easy-template-x": "0.7.1"
  }
```

`index.js` code is as simple as following:-
```js
const fs = require('fs');
const { TemplateHandler } = require('easy-template-x');

async function generate_easytemplatex(data){

// 1. read template file
const templateFile = fs.readFileSync('tag-example.docx');
 
// 2. process the template

const handler = new TemplateHandler();
const doc = await handler.process(templateFile, data);
 
// 3. save output
fs.writeFileSync('myTemplate-output.docx', doc);
}

async function main(){
    try {      
        let result = [ { id: "1", subject: "Topic1"} , { id: "2", subject: "Topic2"} ];
                         await generate_easytemplatex({"issues": result});
    } catch (error) {
        console.log(`error: ${error}`);
    }
  }

 main();
```
Using it like this:-
```sh
node index.js
```

**Comment by alonrbar** [comment]
When I [first found](https://github.com/alonrbar/easy-template-x/commit/9b62694053c9c71a0bf0305e5dbd384effeca309) the bug I was guessing Babel is the source of this issue. It turns out that this is Webpack's fault (https://github.com/webpack/webpack/issues/4240) and the solution is to turn off this webpack config: https://webpack.js.org/configuration/node/#nodebuffer.
Fixing now and will release a new version soon.

**Comment by alonrbar** [comment]
Well, tested it locally and now published v0.7.2. Hopefully this closes this bug for good.
On the bright side, fixing this bug actually reduced the [bundle size](https://bundlephobia.com/result?p=easy-template-x@0.7.2) :)
